[package-test]
  command = 'Rscript'
  args = ['--no-save', '--no-restore', '-e devtools::test()']

[package-build]
  command = 'R'
  args = ['CMD', 'INSTALL', '--no-multiarch', '--with-keep.source', '.']

